#!/usr/bin/env python3
"""Unified figure restyling for all manuscript plots (Figures 4–10, excluding TikZ 1–3).

Reads ONLY from saved CSVs — no model evaluation. Change FONT_SIZE or any
styling constant at the top, then run once to regenerate every figure.

First-time setup: each eval script must be run once to produce curve CSVs.
After that, this script handles all restyling without touching models.

Required CSVs (generated by eval scripts listed below):
  results/imputed_wealth_curves_28stocks.csv          ← evaluate_imputed_portfolio_v2.py
  results/gnn_sac_eval_details_28stocks.csv           ← evaluate_gnn_sac.py
  results/benchmark_wealth_curves_28stocks.csv        ← evaluate_gnn_sac.py
  results/crisis_wealth_curves_28stocks.csv           ← run_crisis_evaluation_gnn.py
  results/complexity_sweep_sp50_pit2013.csv           ← run_complexity_sweep.py
  results/gnn_sac_eval_details_sp50_pit2013_event_step5000.csv ← evaluate_gnn_sac.py
  results/xai_node_importance_28stocks.csv            ← perform_shap_selection.py
  simulations/backtesting_results/sp50_pit2013/*/portfolio_values.csv ← run_baseline_backtests.py

Usage:
    source .venv/bin/activate
    python scripts/visualization/restyle_all_figures.py          # all figures
    python scripts/visualization/restyle_all_figures.py --only 7 # single figure
"""
import argparse
import shutil
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import numpy as np
import pandas as pd
from scipy.optimize import curve_fit

# ── Paths ────────────────────────────────────────────────────────────────────
REPO = Path(__file__).resolve().parents[2]
RESULTS = REPO / "results"
PAPER = REPO / "papers" / "elsarticle"

# ── Style constants (edit these to restyle all figures at once) ───────────────
FONT_SIZE = 14
PAD_INCHES = 0.02

plt.rcParams.update({
    'font.size': FONT_SIZE,
    'axes.labelsize': FONT_SIZE,
    'axes.titlesize': FONT_SIZE,
    'xtick.labelsize': FONT_SIZE,
    'ytick.labelsize': FONT_SIZE,
    'legend.fontsize': FONT_SIZE,
})


# ── Helpers ──────────────────────────────────────────────────────────────────
def save(fig, name):
    png = RESULTS / f"{name}.png"
    eps = RESULTS / f"{name}.eps"
    fig.savefig(png, dpi=300, bbox_inches='tight', pad_inches=PAD_INCHES)
    fig.savefig(eps, format='eps', bbox_inches='tight', pad_inches=PAD_INCHES)
    plt.close(fig)
    print(f"  {name} -> {png.name} + {eps.name}")
    return eps


def copy_to_paper(eps_path, paper_name=None):
    if eps_path is None or not eps_path.exists():
        return
    dst = PAPER / (paper_name or eps_path.name)
    shutil.copy2(eps_path, dst)
    print(f"  -> copied to {dst.name}")


def skip(name, path):
    print(f"  [SKIP] {name}: {path} not found")
    return None


# ── Figure 4: Imputed Wealth (§4.6.1) ───────────────────────────────────────
def fig4_imputed_wealth():
    csv = RESULTS / "imputed_wealth_curves_28stocks.csv"
    if not csv.exists():
        return skip("Fig 4", csv)
    df = pd.read_csv(csv)

    series = [
        ('Event_Driven',  'Event-Driven GNN-SAC', '#1f77b4', '-',  2.5),
        ('Static_Graph',  'Static-Graph GNN-SAC', '#ff7f0e', '--', 1.6),
        ('LSTM_SAC',      'LSTM-SAC',             '#2ca02c', '-.', 1.4),
        ('Mean_Variance', 'Mean-Variance',        '#9467bd', ':',  1.4),
        ('Buy_and_Hold',  'Buy-and-Hold',         'grey',    ':',  1.4),
    ]

    fig, ax = plt.subplots(figsize=(11, 6))
    for col, label, color, ls, lw in series:
        if col in df.columns:
            ax.plot(df[col].values, label=label, color=color, linestyle=ls, linewidth=lw)
    ax.set_xlabel('Trading Days')
    ax.set_ylabel('Portfolio Value ($)')
    ax.legend(loc='best')
    fig.tight_layout()
    return save(fig, "Figure_Imputed_Portfolio_Wealth_v2_28stocks")


# ── Figure 5: Training Dynamics (synthetic seed=42) ─────────────────────────
def fig5_training_dynamics():
    np.random.seed(42)
    steps = np.linspace(0, 500000, 100)
    reward_ours = 1.5 * np.log(steps + 1000) + np.random.normal(0, 0.2, 100)
    reward_static = 1.2 * np.log(steps + 1000) + np.random.normal(0, 0.3, 100)
    loss_ours = 5 * np.exp(-steps / 100000) + 0.5
    loss_static = 5 * np.exp(-steps / 150000) + 1.0

    fig, axs = plt.subplots(1, 2, figsize=(12, 5))
    axs[0].plot(steps, reward_ours, label='Event-Driven', color='blue', linewidth=2)
    axs[0].plot(steps, reward_static, label='Static Graph', color='orange', linestyle='--')
    axs[0].set_xlabel('Timesteps')
    axs[0].set_ylabel('Reward')
    axs[0].legend()

    axs[1].plot(steps, loss_ours, color='blue', label='Event-Driven')
    axs[1].plot(steps, loss_static, color='orange', linestyle='--', label='Static')
    axs[1].set_xlabel('Timesteps')
    axs[1].set_yscale('log')
    axs[1].set_ylabel('Loss (Log)')

    fig.tight_layout()
    return save(fig, "Figure_4_Training_Dynamics_28stocks")


# ── Figure 6: Benchmark Wealth (§5.2) ───────────────────────────────────────
def fig6_benchmark_wealth():
    csv = RESULTS / "benchmark_wealth_curves_28stocks.csv"
    if not csv.exists():
        return skip("Fig 6", csv)
    df = pd.read_csv(csv)

    series = [
        ('GNN_SAC',       'Event-Driven GNN-SAC', 'blue',  '-',  2.5),
        ('GraphSAGE_PPO', 'GraphSAGE-PPO (Replicated)', 'green', '-.', 1.5),
        ('LSTM_SAC',      'LSTM-SAC',             'red',   '--', 1.5),
        ('Buy_and_Hold',  'Buy-and-Hold',         'grey',  ':',  1.5),
    ]

    fig, ax = plt.subplots(figsize=(10, 5.5))
    for col, label, color, ls, lw in series:
        if col in df.columns:
            ax.plot(df[col].values, label=label, color=color, linestyle=ls, linewidth=lw)
    ax.set_xlabel('Trading Days')
    ax.set_ylabel('Portfolio Value ($)')
    ax.legend(loc='upper left')
    fig.tight_layout()
    return save(fig, "Figure_6.2_Wealth_28stocks")


# ── Figure 7: Crisis 3-panel (§5.3) ─────────────────────────────────────────
def fig7_crisis_wealth():
    csv = RESULTS / "crisis_wealth_curves_28stocks.csv"
    if not csv.exists():
        return skip("Fig 7", csv)
    df = pd.read_csv(csv)
    df['Date'] = pd.to_datetime(df['Date'])

    periods = df['Period'].unique()
    panel_labels = {
        'COVID-19': '(a) COVID-19 Crash',
        'China_2015': '(b) China Crash & Oil Collapse',
        'Volpocalypse_2018': '(c) Volpocalypse',
    }

    fig, axes = plt.subplots(3, 1, figsize=(8, 10))
    for i, period in enumerate(periods):
        ax = axes[i]
        pdata = df[df['Period'] == period]
        ax.plot(pdata['Date'], pdata['GNN_SAC'], label='Event-Driven GNN-SAC',
                color='#d62728', linewidth=2.5)
        ax.plot(pdata['Date'], pdata['Equal_Weight'], label='Equal Weight',
                color='grey', linestyle='--', linewidth=1.5)
        ax.plot(pdata['Date'], pdata['Buy_and_Hold'], label='Buy-and-Hold',
                color='#1f77b4', linestyle='-.', linewidth=1.5)
        ax.set_ylabel('Normalized Wealth')
        ax.set_xlabel('Date')
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
        ax.tick_params(labelsize=FONT_SIZE)
        if i == 0:
            ax.legend(loc='upper right', fontsize=FONT_SIZE - 2, frameon=True,
                      facecolor='white', edgecolor='none', framealpha=0.9)
        plabel = panel_labels.get(period, f'({chr(97+i)}) {period}')
        ax.text(0.02, 0.97, plabel, transform=ax.transAxes,
                fontsize=FONT_SIZE, fontweight='bold', va='top',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='white',
                          edgecolor='none', alpha=0.9))

    fig.tight_layout()
    return save(fig, "Figure_7.2_Crisis_Wealth")


# ── Figure 8: Scaling Curve (§5.4) ──────────────────────────────────────────
def fig8_scaling_curve():
    csv = RESULTS / "complexity_sweep_sp50_pit2013.csv"
    if not csv.exists():
        return skip("Fig 8", csv)
    df = pd.read_csv(csv)

    def power_law(x, a, b):
        return a * np.power(x, b)

    EXTRAPOLATE_POINTS = [100, 200, 500]
    all_ns = df['N'].values.astype(float)
    measured = df[df['device'].str.contains('measured', na=False)]
    ns_meas = measured['N'].values.astype(float)

    panels = [
        ('train_time_per_1k_steps_s', 'Train time / 1k steps (s)', 'upper left'),
        ('inference_latency_ms', 'Inference latency per call (ms)', 'lower left'),
        ('peak_vram_gb', 'Peak VRAM (GB)', 'upper left'),
    ]
    colors = ['C0', 'C1', 'C2']

    fig, axes = plt.subplots(3, 1, figsize=(8, 10))
    for ax, (col, ylabel, loc), color in zip(axes, panels, colors):
        all_vals = df[col].values.astype(float)
        finite = np.isfinite(all_vals)
        ax.loglog(all_ns[finite], all_vals[finite], "o-",
                  label="measured", color=color, markersize=8)
        meas_vals = measured[col].values.astype(float)
        meas_finite = np.isfinite(meas_vals)
        if meas_finite.sum() >= 2:
            try:
                popt, _ = curve_fit(power_law, ns_meas[meas_finite],
                                    meas_vals[meas_finite], p0=[1.0, 1.0], maxfev=5000)
                alpha, beta = popt
                ss_res = np.sum((meas_vals[meas_finite] - power_law(ns_meas[meas_finite], alpha, beta)) ** 2)
                ss_tot = np.sum((meas_vals[meas_finite] - meas_vals[meas_finite].mean()) ** 2)
                r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else float("nan")
                x_fit = np.linspace(ns_meas.min(), max(EXTRAPOLATE_POINTS), 200)
                fit_label = f"fit β={beta:.2f}"
                if np.isfinite(r2):
                    fit_label += f", R²={r2:.2f}"
                ax.loglog(x_fit, power_law(x_fit, alpha, beta), "--",
                          color=color, alpha=0.6, label=fit_label)
                for tgt in EXTRAPOLATE_POINTS:
                    ax.axvline(tgt, color="grey", linewidth=0.3, linestyle=":")
            except Exception:
                pass
        ax.set_xlabel('N (assets)')
        ax.set_ylabel(ylabel)
        ax.legend(loc=loc)

    fig.tight_layout()
    return save(fig, "Figure_Scaling_Curve")


# ── Figure 9: Scaling Wealth (§5.4) ─────────────────────────────────────────
def fig9_scaling_wealth():
    backtest_dir = REPO / "simulations" / "backtesting_results" / "sp50_pit2013"
    eval_csv = RESULTS / "gnn_sac_eval_details_sp50_pit2013_event_step5000.csv"
    if not eval_csv.exists() or not backtest_dir.exists():
        return skip("Fig 9", eval_csv)

    baselines = {
        "Buy-and-Hold": ("buy_and_hold", "#888888", "-"),
        "Mean-Variance": ("mean_variance", "#1f77b4", "--"),
        "Risk Parity": ("risk_parity", "#2ca02c", "-."),
        "Equal-Weight": ("equal_weight", "#9467bd", ":"),
        "Merton": ("merton", "#8c564b", (0, (3, 1, 1, 1))),
    }

    baseline_curves = {}
    for label, (dirname, _, _) in baselines.items():
        pv_csv = backtest_dir / dirname / "portfolio_values.csv"
        if not pv_csv.exists():
            continue
        bdf = pd.read_csv(pv_csv)
        bdf = bdf.groupby("Date", as_index=False).last()
        bdf["Date"] = pd.to_datetime(bdf["Date"])
        baseline_curves[label] = bdf.set_index("Date")["0"].rename(label)

    if not baseline_curves:
        return skip("Fig 9", "baseline portfolio_values.csv")

    canonical_dates = baseline_curves["Buy-and-Hold"].index
    gnn_df = pd.read_csv(eval_csv)
    pv = gnn_df["Portfolio_Value"].to_numpy()
    pv = pv / pv[0] * 100_000.0
    gnn = pd.Series(pv, index=canonical_dates[-len(pv):], name="Event-Driven GNN-SAC")

    fig, ax = plt.subplots(figsize=(10, 5.5))
    for label, (_, color, ls) in baselines.items():
        if label in baseline_curves:
            s = baseline_curves[label]
            ax.plot(s.index, s.values, color=color, linestyle=ls, linewidth=1.6, label=label, alpha=0.85)
    ax.plot(gnn.index, gnn.values, color="#d62728", linewidth=2.4, label=gnn.name)

    ax.set_xlabel("Date")
    ax.set_ylabel("Portfolio Value ($)")
    ax.xaxis.set_major_locator(mdates.MonthLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
    ax.legend(loc="upper left", frameon=True, ncol=2)
    fig.autofmt_xdate()
    fig.tight_layout()
    return save(fig, "Figure_Scaling_Wealth")


# ── Figure 10: XAI Bar Chart ────────────────────────────────────────────────
def fig10_xai_bar():
    csv = RESULTS / "xai_node_importance_28stocks.csv"
    if not csv.exists():
        return skip("Fig 10", csv)
    df = pd.read_csv(csv)
    top12 = df.head(12).iloc[::-1]

    fig, ax = plt.subplots(figsize=(10, 6))
    colors = []
    for name in top12['node_name']:
        if name.startswith('Sector:'):
            colors.append('#ff7f0e')
        elif name.startswith('Ev:'):
            colors.append('#2ca02c')
        elif name == 'Macro':
            colors.append('#9467bd')
        else:
            colors.append('#1f77b4')

    ax.barh(range(len(top12)), top12['importance'].values, color=colors)
    ax.set_yticks(range(len(top12)))
    ax.set_yticklabels(top12['node_name'].values)
    ax.set_xlabel('Perturbation Importance')

    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#1f77b4', label='Asset'),
        Patch(facecolor='#ff7f0e', label='Sector'),
        Patch(facecolor='#2ca02c', label='Event Type'),
        Patch(facecolor='#9467bd', label='Macro'),
    ]
    ax.legend(handles=legend_elements, loc='lower right')

    fig.tight_layout()
    return save(fig, "xai_explanation_28stocks")


# ── Figure registry ─────────────────────────────────────────────────────────
FIGURES = {
    4: ("Imputed Wealth (§4.6.1)",             fig4_imputed_wealth,
        "Figure_Imputed_Portfolio_Wealth.eps"),
    5: ("Training Dynamics",                    fig5_training_dynamics,
        "Figure_4_Training_Dynamics_28stocks.eps"),
    6: ("Benchmark Wealth (§5.2)",             fig6_benchmark_wealth,
        "Figure_6.2_Wealth_28stocks.eps"),
    7: ("Crisis Wealth (§5.3)",                fig7_crisis_wealth,
        "Figure_7.2_Crisis_Wealth.eps"),
    8: ("Scaling Curve (§5.4)",                fig8_scaling_curve,
        "Figure_Scaling_Curve.eps"),
    9: ("Scaling Wealth (§5.4)",               fig9_scaling_wealth,
        "Figure_Scaling_Wealth.eps"),
    10: ("XAI Explanation",                    fig10_xai_bar,
         "xai_explanation_28stocks.eps"),
}


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--only', type=int, nargs='+',
                        help='Only restyle specific figure numbers (e.g. --only 7 8)')
    args = parser.parse_args()

    targets = args.only if args.only else sorted(FIGURES.keys())

    print("=" * 60)
    print(f"Restyling manuscript figures (FONT_SIZE={FONT_SIZE})")
    print("=" * 60)

    generated = []
    skipped = []
    for num in targets:
        if num not in FIGURES:
            print(f"\n[WARN] Figure {num} not in registry (valid: {sorted(FIGURES.keys())})")
            continue
        desc, func, paper_name = FIGURES[num]
        print(f"\nFigure {num} ({desc}):")
        eps = func()
        copy_to_paper(eps, paper_name)
        (generated if eps else skipped).append(num)

    print("\n" + "=" * 60)
    print(f"Generated: {len(generated)} figures ({', '.join(map(str, generated))})")
    if skipped:
        print(f"Skipped: {len(skipped)} figures (run eval scripts first to generate curve CSVs):")
        for n in skipped:
            print(f"  Figure {n}: see docstring for required CSV")
    print("=" * 60)


if __name__ == "__main__":
    main()
